#!/bin/bash
# Quick Start: Sistema Multi-Acelerador Optimizado

echo "🚀 Sistema Multi-Acelerador Configurado"
echo ""
echo "Tu sistema tiene 3 aceleradores disponibles:"
echo ""
echo "1️⃣  CPU (24 cores)"
echo "   └─ Uso: LLMs pequeños, procesamiento general"
echo ""
echo "2️⃣  iGPU Intel ARL (Vulkan)"
echo "   └─ Uso: Ollama (LLMs 3-7B), codificación video"
echo ""
echo "3️⃣  NPU Intel AI Boost 3720 (~10 TOPS)"
echo "   └─ Uso: Embeddings, clasificación, NO LLMs"
echo ""
echo "────────────────────────────────────────────"
echo ""
echo "📦 Scripts disponibles:"
echo ""
echo "  ./setup-multi-accelerator.sh"
echo "    └─ Optimiza CPU, verifica GPU/NPU, configura sistema"
echo ""
echo "  ./optimize-swap.sh"
echo "    └─ Aumenta swap 8GB→32GB y reduce swappiness"
echo ""
echo "  ./npu-embeddings-service.py demo"
echo "    └─ Demo de embeddings en NPU (sentence-transformers)"
echo ""
echo "  ./benchmark-npu.py"
echo "    └─ Benchmark CPU vs GPU vs NPU"
echo ""
echo "────────────────────────────────────────────"
echo ""
echo "🦙 Ollama (iGPU) - Estado:"
docker ps --filter "name=ollama" --format "  ✅ {{.Names}} ({{.Status}})" 2>/dev/null || echo "  ⚠️  No corriendo"
echo ""
echo "🧠 NPU - Estado:"
if [ -e /dev/accel/accel0 ]; then
    echo "  ✅ Disponible: /dev/accel/accel0"
else
    echo "  ❌ No detectado"
fi
echo ""
echo "────────────────────────────────────────────"
echo ""
echo "⚡ Quick Commands:"
echo ""
echo "  # Activar entorno OpenVINO+NPU"
echo "  source ~/.openclaw/workspace/openvino-genai-env/bin/activate"
echo ""
echo "  # Test embeddings en NPU"
echo "  python npu-embeddings-service.py demo"
echo ""
echo "  # LLM en Ollama (iGPU)"
echo "  docker exec -it ollama-intel-arc ollama run llama3.2:3b"
echo ""
echo "  # Ver uso de GPU"
echo "  intel_gpu_top"
echo ""
echo "────────────────────────────────────────────"
echo ""
echo "📊 Benchmark de tu último test:"
echo ""
echo "  CPU:  40.86 tokens/s  ⚡ (mejor para LLMs pequeños)"
echo "  GPU:  37.09 tokens/s  🎮 (actual en Ollama)"
echo "  NPU:   0.97 tokens/s  🧠 (NO usar para LLMs)"
echo ""
echo "💡 Conclusión: Mantén Ollama en iGPU, usa NPU para embeddings"
echo ""
